// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmckY3YoMisZ0cDQ1jaJAgJogTnd1HEHQ',
    appId: '1:634708531015:web:97f17e3bd369580de79e62',
    messagingSenderId: '634708531015',
    projectId: 'entinkost-14af0',
    authDomain: 'entinkost-14af0.firebaseapp.com',
    storageBucket: 'entinkost-14af0.firebasestorage.app',
    measurementId: 'G-40GDFN57SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9E_El8mmW9Hqif2FqJA6PFEMYsJf7HbI',
    appId: '1:634708531015:android:5a3744a6f67b27f1e79e62',
    messagingSenderId: '634708531015',
    projectId: 'entinkost-14af0',
    storageBucket: 'entinkost-14af0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAITuo2DNR4xMqNzGxhGqteltcC9GsYXNQ',
    appId: '1:634708531015:ios:0473f1ace4e9b270e79e62',
    messagingSenderId: '634708531015',
    projectId: 'entinkost-14af0',
    storageBucket: 'entinkost-14af0.firebasestorage.app',
    iosBundleId: 'com.example.kost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAITuo2DNR4xMqNzGxhGqteltcC9GsYXNQ',
    appId: '1:634708531015:ios:0473f1ace4e9b270e79e62',
    messagingSenderId: '634708531015',
    projectId: 'entinkost-14af0',
    storageBucket: 'entinkost-14af0.firebasestorage.app',
    iosBundleId: 'com.example.kost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmckY3YoMisZ0cDQ1jaJAgJogTnd1HEHQ',
    appId: '1:634708531015:web:d6804703bf0b379de79e62',
    messagingSenderId: '634708531015',
    projectId: 'entinkost-14af0',
    authDomain: 'entinkost-14af0.firebaseapp.com',
    storageBucket: 'entinkost-14af0.firebasestorage.app',
    measurementId: 'G-1DYX25M00Y',
  );
}
